version: "2"

formatters:
  enable:
    - goimports
    - gofumpt

  settings:
    goimports:
      local-prefixes:
        - github.com/codeboyzhou/sql-copilot
    gofumpt:
      extra-rules: true
      module-path: github.com/codeboyzhou/sql-copilot

linters:
  settings:
    staticcheck:
      checks:
        # The default config:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        # Changes to the default config:
        - -QF1001 # Exclude "Apply De Morgan's law"
        - -QF1008 # Exclude "Omit embedded fields from selector expression"
 